version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vehicles_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./vehicles_server
    container_name: vehicles_server
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/vehicles_db
    volumes:
      - ./vehicles_server:/app
    ports:
      - "3030:3030"

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./vehicles_front:/app
    ports:
      - "4200:4200"
    command: sh -c "npm install && npm run start -- --host 0.0.0.0"

volumes:
  pgdata:
